export interface WilayaInfo {
  code: string;
  nameAr: string;
  nameFr: string;
  region: 'الشمال الأوسط' | 'الشرق' | 'الغرب' | 'الهضاب العليا' | 'الجنوب';
  // خشنة (ثقيلة >2.3 كغ)
  khashna_farmer: number;
  khashna_slaughter: number;
  khashna_intermediary: number;
  // متوسطة (1.6-2.3 كغ)
  motawassita_farmer: number;
  motawassita_slaughter: number;
  motawassita_intermediary: number;
  // رقيقة (خفيفة <1.6 كغ)
  raqiqa_farmer: number;
  raqiqa_slaughter: number;
  raqiqa_intermediary: number;
  trend: 'up' | 'down' | 'stable';
  trendPercent: string;
}

export const ALGERIA_WILAYAS: WilayaInfo[] = [
  { code: '01', nameAr: 'أدرار', nameFr: 'Adrar', region: 'الجنوب', khashna_farmer: 355, khashna_slaughter: 345, khashna_intermediary: 365, motawassita_farmer: 340, motawassita_slaughter: 330, motawassita_intermediary: 350, raqiqa_farmer: 325, raqiqa_slaughter: 315, raqiqa_intermediary: 335, trend: 'stable', trendPercent: '0.0%' },
  { code: '02', nameAr: 'الشلف', nameFr: 'Chlef', region: 'الغرب', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.5%' },
  { code: '03', nameAr: 'الأغواط', nameFr: 'Laghouat', region: 'الهضاب العليا', khashna_farmer: 330, khashna_slaughter: 320, khashna_intermediary: 340, motawassita_farmer: 315, motawassita_slaughter: 305, motawassita_intermediary: 325, raqiqa_farmer: 300, raqiqa_slaughter: 290, raqiqa_intermediary: 310, trend: 'stable', trendPercent: '0.0%' },
  { code: '04', nameAr: 'أم البواقي', nameFr: 'Oum El Bouaghi', region: 'الشرق', khashna_farmer: 310, khashna_slaughter: 300, khashna_intermediary: 320, motawassita_farmer: 295, motawassita_slaughter: 285, motawassita_intermediary: 305, raqiqa_farmer: 280, raqiqa_slaughter: 270, raqiqa_intermediary: 290, trend: 'down', trendPercent: '-2.1%' },
  { code: '05', nameAr: 'باتنة', nameFr: 'Batna', region: 'الشرق', khashna_farmer: 305, khashna_slaughter: 295, khashna_intermediary: 315, motawassita_farmer: 290, motawassita_slaughter: 280, motawassita_intermediary: 300, raqiqa_farmer: 275, raqiqa_slaughter: 265, raqiqa_intermediary: 285, trend: 'down', trendPercent: '-3.0%' },
  { code: '06', nameAr: 'بجاية', nameFr: 'Béjaïa', region: 'الشرق', khashna_farmer: 325, khashna_slaughter: 315, khashna_intermediary: 335, motawassita_farmer: 310, motawassita_slaughter: 300, motawassita_intermediary: 320, raqiqa_farmer: 295, raqiqa_slaughter: 285, raqiqa_intermediary: 305, trend: 'stable', trendPercent: '+0.5%' },
  { code: '07', nameAr: 'بسكرة', nameFr: 'Biskra', region: 'الجنوب', khashna_farmer: 325, khashna_slaughter: 315, khashna_intermediary: 335, motawassita_farmer: 310, motawassita_slaughter: 300, motawassita_intermediary: 320, raqiqa_farmer: 295, raqiqa_slaughter: 285, raqiqa_intermediary: 305, trend: 'down', trendPercent: '-1.2%' },
  { code: '08', nameAr: 'بشار', nameFr: 'Béchar', region: 'الجنوب', khashna_farmer: 360, khashna_slaughter: 350, khashna_intermediary: 370, motawassita_farmer: 345, motawassita_slaughter: 335, motawassita_intermediary: 355, raqiqa_farmer: 330, raqiqa_slaughter: 320, raqiqa_intermediary: 340, trend: 'stable', trendPercent: '0.0%' },
  { code: '09', nameAr: 'البليدة', nameFr: 'Blida', region: 'الشمال الأوسط', khashna_farmer: 310, khashna_slaughter: 300, khashna_intermediary: 320, motawassita_farmer: 295, motawassita_slaughter: 285, motawassita_intermediary: 305, raqiqa_farmer: 280, raqiqa_slaughter: 270, raqiqa_intermediary: 290, trend: 'down', trendPercent: '-2.5%' },
  { code: '10', nameAr: 'البويرة', nameFr: 'Bouira', region: 'الشمال الأوسط', khashna_farmer: 305, khashna_slaughter: 295, khashna_intermediary: 315, motawassita_farmer: 290, motawassita_slaughter: 280, motawassita_intermediary: 300, raqiqa_farmer: 275, raqiqa_slaughter: 265, raqiqa_intermediary: 285, trend: 'down', trendPercent: '-3.2%' },
  { code: '11', nameAr: 'تمنراست', nameFr: 'Tamanrasset', region: 'الجنوب', khashna_farmer: 380, khashna_slaughter: 370, khashna_intermediary: 390, motawassita_farmer: 365, motawassita_slaughter: 355, motawassita_intermediary: 375, raqiqa_farmer: 350, raqiqa_slaughter: 340, raqiqa_intermediary: 360, trend: 'up', trendPercent: '+1.8%' },
  { code: '12', nameAr: 'تبسة', nameFr: 'Tébessa', region: 'الشرق', khashna_farmer: 320, khashna_slaughter: 310, khashna_intermediary: 330, motawassita_farmer: 305, motawassita_slaughter: 295, motawassita_intermediary: 315, raqiqa_farmer: 290, raqiqa_slaughter: 280, raqiqa_intermediary: 300, trend: 'stable', trendPercent: '0.0%' },
  { code: '13', nameAr: 'تلمسان', nameFr: 'Tlemcen', region: 'الغرب', khashna_farmer: 325, khashna_slaughter: 315, khashna_intermediary: 335, motawassita_farmer: 310, motawassita_slaughter: 300, motawassita_intermediary: 320, raqiqa_farmer: 295, raqiqa_slaughter: 285, raqiqa_intermediary: 305, trend: 'stable', trendPercent: '-0.8%' },
  { code: '14', nameAr: 'تيارت', nameFr: 'Tiaret', region: 'الهضاب العليا', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.0%' },
  { code: '15', nameAr: 'تيزي وزو', nameFr: 'Tizi Ouzou', region: 'الشمال الأوسط', khashna_farmer: 320, khashna_slaughter: 310, khashna_intermediary: 330, motawassita_farmer: 305, motawassita_slaughter: 295, motawassita_intermediary: 315, raqiqa_farmer: 290, raqiqa_slaughter: 280, raqiqa_intermediary: 300, trend: 'stable', trendPercent: '0.0%' },
  { code: '16', nameAr: 'الجزائر العاصمة', nameFr: 'Alger', region: 'الشمال الأوسط', khashna_farmer: 330, khashna_slaughter: 320, khashna_intermediary: 340, motawassita_farmer: 315, motawassita_slaughter: 305, motawassita_intermediary: 325, raqiqa_farmer: 300, raqiqa_slaughter: 290, raqiqa_intermediary: 310, trend: 'up', trendPercent: '+1.2%' },
  { code: '17', nameAr: 'الجلفة', nameFr: 'Djelfa', region: 'الهضاب العليا', khashna_farmer: 320, khashna_slaughter: 310, khashna_intermediary: 330, motawassita_farmer: 305, motawassita_slaughter: 295, motawassita_intermediary: 315, raqiqa_farmer: 290, raqiqa_slaughter: 280, raqiqa_intermediary: 300, trend: 'down', trendPercent: '-1.5%' },
  { code: '18', nameAr: 'جيجل', nameFr: 'Jijel', region: 'الشرق', khashna_farmer: 325, khashna_slaughter: 315, khashna_intermediary: 335, motawassita_farmer: 310, motawassita_slaughter: 300, motawassita_intermediary: 320, raqiqa_farmer: 295, raqiqa_slaughter: 285, raqiqa_intermediary: 305, trend: 'stable', trendPercent: '0.0%' },
  { code: '19', nameAr: 'سطيف', nameFr: 'Sétif', region: 'الشرق', khashna_farmer: 305, khashna_slaughter: 295, khashna_intermediary: 315, motawassita_farmer: 290, motawassita_slaughter: 280, motawassita_intermediary: 300, raqiqa_farmer: 275, raqiqa_slaughter: 265, raqiqa_intermediary: 285, trend: 'down', trendPercent: '-3.5%' },
  { code: '20', nameAr: 'سعيدة', nameFr: 'Saïda', region: 'الغرب', khashna_farmer: 320, khashna_slaughter: 310, khashna_intermediary: 330, motawassita_farmer: 305, motawassita_slaughter: 295, motawassita_intermediary: 315, raqiqa_farmer: 290, raqiqa_slaughter: 280, raqiqa_intermediary: 300, trend: 'stable', trendPercent: '0.0%' },
  { code: '21', nameAr: 'سكيكدة', nameFr: 'Skikda', region: 'الشرق', khashna_farmer: 325, khashna_slaughter: 315, khashna_intermediary: 335, motawassita_farmer: 310, motawassita_slaughter: 300, motawassita_intermediary: 320, raqiqa_farmer: 295, raqiqa_slaughter: 285, raqiqa_intermediary: 305, trend: 'up', trendPercent: '+0.8%' },
  { code: '22', nameAr: 'سيدي بلعباس', nameFr: 'Sidi Bel Abbès', region: 'الغرب', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.2%' },
  { code: '23', nameAr: 'عنابة', nameFr: 'Annaba', region: 'الشرق', khashna_farmer: 330, khashna_slaughter: 320, khashna_intermediary: 340, motawassita_farmer: 315, motawassita_slaughter: 305, motawassita_intermediary: 325, raqiqa_farmer: 300, raqiqa_slaughter: 290, raqiqa_intermediary: 310, trend: 'stable', trendPercent: '0.0%' },
  { code: '24', nameAr: 'قالمة', nameFr: 'Guelma', region: 'الشرق', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.8%' },
  { code: '25', nameAr: 'قسنطينة', nameFr: 'Constantine', region: 'الشرق', khashna_farmer: 320, khashna_slaughter: 310, khashna_intermediary: 330, motawassita_farmer: 305, motawassita_slaughter: 295, motawassita_intermediary: 315, raqiqa_farmer: 290, raqiqa_slaughter: 280, raqiqa_intermediary: 300, trend: 'down', trendPercent: '-1.5%' },
  { code: '26', nameAr: 'المدية', nameFr: 'Médéa', region: 'الشمال الأوسط', khashna_farmer: 305, khashna_slaughter: 295, khashna_intermediary: 315, motawassita_farmer: 290, motawassita_slaughter: 280, motawassita_intermediary: 300, raqiqa_farmer: 275, raqiqa_slaughter: 265, raqiqa_intermediary: 285, trend: 'down', trendPercent: '-2.8%' },
  { code: '27', nameAr: 'مستغانم', nameFr: 'Mostaganem', region: 'الغرب', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'stable', trendPercent: '-0.5%' },
  { code: '28', nameAr: 'المسيلة', nameFr: 'M\'Sila', region: 'الهضاب العليا', khashna_farmer: 310, khashna_slaughter: 300, khashna_intermediary: 320, motawassita_farmer: 295, motawassita_slaughter: 285, motawassita_intermediary: 305, raqiqa_farmer: 280, raqiqa_slaughter: 270, raqiqa_intermediary: 290, trend: 'down', trendPercent: '-2.0%' },
  { code: '29', nameAr: 'معسكر', nameFr: 'Mascara', region: 'الغرب', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.4%' },
  { code: '30', nameAr: 'ورقلة', nameFr: 'Ouargla', region: 'الجنوب', khashna_farmer: 350, khashna_slaughter: 340, khashna_intermediary: 360, motawassita_farmer: 335, motawassita_slaughter: 325, motawassita_intermediary: 345, raqiqa_farmer: 320, raqiqa_slaughter: 310, raqiqa_intermediary: 330, trend: 'stable', trendPercent: '0.0%' },
  { code: '31', nameAr: 'وهران', nameFr: 'Oran', region: 'الغرب', khashna_farmer: 330, khashna_slaughter: 320, khashna_intermediary: 340, motawassita_farmer: 315, motawassita_slaughter: 305, motawassita_intermediary: 325, raqiqa_farmer: 300, raqiqa_slaughter: 290, raqiqa_intermediary: 310, trend: 'up', trendPercent: '+1.0%' },
  { code: '32', nameAr: 'البيض', nameFr: 'El Bayadh', region: 'الهضاب العليا', khashna_farmer: 330, khashna_slaughter: 320, khashna_intermediary: 340, motawassita_farmer: 315, motawassita_slaughter: 305, motawassita_intermediary: 325, raqiqa_farmer: 300, raqiqa_slaughter: 290, raqiqa_intermediary: 310, trend: 'stable', trendPercent: '0.0%' },
  { code: '33', nameAr: 'إليزي', nameFr: 'Illizi', region: 'الجنوب', khashna_farmer: 385, khashna_slaughter: 375, khashna_intermediary: 395, motawassita_farmer: 370, motawassita_slaughter: 360, motawassita_intermediary: 380, raqiqa_farmer: 355, raqiqa_slaughter: 345, raqiqa_intermediary: 365, trend: 'up', trendPercent: '+2.0%' },
  { code: '34', nameAr: 'برج بوعريريج', nameFr: 'Bordj Bou Arréridj', region: 'الشرق', khashna_farmer: 310, khashna_slaughter: 300, khashna_intermediary: 320, motawassita_farmer: 295, motawassita_slaughter: 285, motawassita_intermediary: 305, raqiqa_farmer: 280, raqiqa_slaughter: 270, raqiqa_intermediary: 290, trend: 'down', trendPercent: '-2.2%' },
  { code: '35', nameAr: 'بومرداس', nameFr: 'Boumerdès', region: 'الشمال الأوسط', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.5%' },
  { code: '36', nameAr: 'الطارف', nameFr: 'El Tarf', region: 'الشرق', khashna_farmer: 325, khashna_slaughter: 315, khashna_intermediary: 335, motawassita_farmer: 310, motawassita_slaughter: 300, motawassita_intermediary: 320, raqiqa_farmer: 295, raqiqa_slaughter: 285, raqiqa_intermediary: 305, trend: 'stable', trendPercent: '0.0%' },
  { code: '37', nameAr: 'تندوف', nameFr: 'Tindouf', region: 'الجنوب', khashna_farmer: 380, khashna_slaughter: 370, khashna_intermediary: 390, motawassita_farmer: 365, motawassita_slaughter: 355, motawassita_intermediary: 375, raqiqa_farmer: 350, raqiqa_slaughter: 340, raqiqa_intermediary: 360, trend: 'stable', trendPercent: '0.0%' },
  { code: '38', nameAr: 'تيسمسيلت', nameFr: 'Tissemsilt', region: 'الهضاب العليا', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.0%' },
  { code: '39', nameAr: 'الوادي', nameFr: 'El Oued', region: 'الجنوب', khashna_farmer: 340, khashna_slaughter: 330, khashna_intermediary: 350, motawassita_farmer: 325, motawassita_slaughter: 315, motawassita_intermediary: 335, raqiqa_farmer: 310, raqiqa_slaughter: 300, raqiqa_intermediary: 320, trend: 'stable', trendPercent: '0.0%' },
  { code: '40', nameAr: 'خنشلة', nameFr: 'Khenchela', region: 'الشرق', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.2%' },
  { code: '41', nameAr: 'سوق أهراس', nameFr: 'Souk Ahras', region: 'الشرق', khashna_farmer: 320, khashna_slaughter: 310, khashna_intermediary: 330, motawassita_farmer: 305, motawassita_slaughter: 295, motawassita_intermediary: 315, raqiqa_farmer: 290, raqiqa_slaughter: 280, raqiqa_intermediary: 300, trend: 'stable', trendPercent: '0.0%' },
  { code: '42', nameAr: 'تيبازة', nameFr: 'Tipaza', region: 'الشمال الأوسط', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.8%' },
  { code: '43', nameAr: 'ميلة', nameFr: 'Mila', region: 'الشرق', khashna_farmer: 310, khashna_slaughter: 300, khashna_intermediary: 320, motawassita_farmer: 295, motawassita_slaughter: 285, motawassita_intermediary: 305, raqiqa_farmer: 280, raqiqa_slaughter: 270, raqiqa_intermediary: 290, trend: 'down', trendPercent: '-2.0%' },
  { code: '44', nameAr: 'عين الدفلى', nameFr: 'Aïn Defla', region: 'الشمال الأوسط', khashna_farmer: 310, khashna_slaughter: 300, khashna_intermediary: 320, motawassita_farmer: 295, motawassita_slaughter: 285, motawassita_intermediary: 305, raqiqa_farmer: 280, raqiqa_slaughter: 270, raqiqa_intermediary: 290, trend: 'down', trendPercent: '-2.4%' },
  { code: '45', nameAr: 'النعامة', nameFr: 'Naâma', region: 'الهضاب العليا', khashna_farmer: 335, khashna_slaughter: 325, khashna_intermediary: 345, motawassita_farmer: 320, motawassita_slaughter: 310, motawassita_intermediary: 330, raqiqa_farmer: 305, raqiqa_slaughter: 295, raqiqa_intermediary: 315, trend: 'stable', trendPercent: '0.0%' },
  { code: '46', nameAr: 'عين تموشنت', nameFr: 'Aïn Témouchent', region: 'الغرب', khashna_farmer: 320, khashna_slaughter: 310, khashna_intermediary: 330, motawassita_farmer: 305, motawassita_slaughter: 295, motawassita_intermediary: 315, raqiqa_farmer: 290, raqiqa_slaughter: 280, raqiqa_intermediary: 300, trend: 'stable', trendPercent: '0.0%' },
  { code: '47', nameAr: 'غرداية', nameFr: 'Ghardaïa', region: 'الجنوب', khashna_farmer: 340, khashna_slaughter: 330, khashna_intermediary: 350, motawassita_farmer: 325, motawassita_slaughter: 315, motawassita_intermediary: 335, raqiqa_farmer: 310, raqiqa_slaughter: 300, raqiqa_intermediary: 320, trend: 'down', trendPercent: '-0.8%' },
  { code: '48', nameAr: 'غليزان', nameFr: 'Relizane', region: 'الغرب', khashna_farmer: 315, khashna_slaughter: 305, khashna_intermediary: 325, motawassita_farmer: 300, motawassita_slaughter: 290, motawassita_intermediary: 310, raqiqa_farmer: 285, raqiqa_slaughter: 275, raqiqa_intermediary: 295, trend: 'down', trendPercent: '-1.5%' },
  { code: '49', nameAr: 'تيميمون', nameFr: 'Timimoun', region: 'الجنوب', khashna_farmer: 360, khashna_slaughter: 350, khashna_intermediary: 370, motawassita_farmer: 345, motawassita_slaughter: 335, motawassita_intermediary: 355, raqiqa_farmer: 330, raqiqa_slaughter: 320, raqiqa_intermediary: 340, trend: 'stable', trendPercent: '0.0%' },
  { code: '50', nameAr: 'برج باجي مختار', nameFr: 'Bordj Badji Mokhtar', region: 'الجنوب', khashna_farmer: 385, khashna_slaughter: 375, khashna_intermediary: 395, motawassita_farmer: 370, motawassita_slaughter: 360, motawassita_intermediary: 380, raqiqa_farmer: 355, raqiqa_slaughter: 345, raqiqa_intermediary: 365, trend: 'stable', trendPercent: '0.0%' },
  { code: '51', nameAr: 'أولاد جلال', nameFr: 'Ouled Djellal', region: 'الجنوب', khashna_farmer: 330, khashna_slaughter: 320, khashna_intermediary: 340, motawassita_farmer: 315, motawassita_slaughter: 305, motawassita_intermediary: 325, raqiqa_farmer: 300, raqiqa_slaughter: 290, raqiqa_intermediary: 310, trend: 'down', trendPercent: '-1.0%' },
  { code: '52', nameAr: 'بني عباس', nameFr: 'Béni Abbès', region: 'الجنوب', khashna_farmer: 360, khashna_slaughter: 350, khashna_intermediary: 370, motawassita_farmer: 345, motawassita_slaughter: 335, motawassita_intermediary: 355, raqiqa_farmer: 330, raqiqa_slaughter: 320, raqiqa_intermediary: 340, trend: 'stable', trendPercent: '0.0%' },
  { code: '53', nameAr: 'عين صالح', nameFr: 'In Salah', region: 'الجنوب', khashna_farmer: 375, khashna_slaughter: 365, khashna_intermediary: 385, motawassita_farmer: 360, motawassita_slaughter: 350, motawassita_intermediary: 370, raqiqa_farmer: 345, raqiqa_slaughter: 335, raqiqa_intermediary: 355, trend: 'stable', trendPercent: '0.0%' },
  { code: '54', nameAr: 'عين قزام', nameFr: 'In Guezzam', region: 'الجنوب', khashna_farmer: 390, khashna_slaughter: 380, khashna_intermediary: 400, motawassita_farmer: 375, motawassita_slaughter: 365, motawassita_intermediary: 385, raqiqa_farmer: 360, raqiqa_slaughter: 350, raqiqa_intermediary: 370, trend: 'stable', trendPercent: '0.0%' },
  { code: '55', nameAr: 'تقرت', nameFr: 'Touggourt', region: 'الجنوب', khashna_farmer: 345, khashna_slaughter: 335, khashna_intermediary: 355, motawassita_farmer: 330, motawassita_slaughter: 320, motawassita_intermediary: 340, raqiqa_farmer: 315, raqiqa_slaughter: 305, raqiqa_intermediary: 325, trend: 'stable', trendPercent: '0.0%' },
  { code: '56', nameAr: 'جانت', nameFr: 'Djanet', region: 'الجنوب', khashna_farmer: 385, khashna_slaughter: 375, khashna_intermediary: 395, motawassita_farmer: 370, motawassita_slaughter: 360, motawassita_intermediary: 380, raqiqa_farmer: 355, raqiqa_slaughter: 345, raqiqa_intermediary: 365, trend: 'stable', trendPercent: '0.0%' },
  { code: '57', nameAr: 'المغير', nameFr: 'El M\'Ghair', region: 'الجنوب', khashna_farmer: 340, khashna_slaughter: 330, khashna_intermediary: 350, motawassita_farmer: 325, motawassita_slaughter: 315, motawassita_intermediary: 335, raqiqa_farmer: 310, raqiqa_slaughter: 300, raqiqa_intermediary: 320, trend: 'stable', trendPercent: '0.0%' },
  { code: '58', nameAr: 'المنيعة', nameFr: 'El Meniaa', region: 'الجنوب', khashna_farmer: 350, khashna_slaughter: 340, khashna_intermediary: 360, motawassita_farmer: 335, motawassita_slaughter: 325, motawassita_intermediary: 345, raqiqa_farmer: 320, raqiqa_slaughter: 310, raqiqa_intermediary: 330, trend: 'stable', trendPercent: '0.0%' },
];

export function getWilayaByCode(code: string): WilayaInfo | undefined {
  return ALGERIA_WILAYAS.find((w) => w.code === code);
}
